server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notebook-shop
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: Note-Book
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
    drop-first: false

logging:
  level:
    liquibase: DEBUG